---
- hosts: all
  tasks:
    - name: Running the command => {{ command }}
      shell: "{{ command }} > /var/lib/dokku/data/storage/t2d"
      ignore_errors: True
      async: 3600 # Maximum allowed time in Seconds
      poll: 10