---
- hosts: all
  tasks:
    - name: Running the command => {{ command }}
      shell: "{{ command }} > /opt/t2d/log.txt"
      ignore_errors: True
      async: 3600 # Maximum allowed time in Seconds
      poll: 10