---
- hosts: all
  tasks:
    - name: Building the app via github repo
      shell: dokku git:sync --build {{ appTitle }} {{ repo }} > /opt/t2d/log.txt
      ignore_errors: True
      async: 3600 # Maximum allowed time in Seconds
      poll: 0