---
- name: Send the necessary files.
  hosts: all
  tasks:
    - name: Create t2d directory
      file:
        path: /opt/t2d
        state: directory

    - name: Uploading files to users server
      copy:
        src: ../../../lib/{{ item }}
        dest: /opt/t2d/{{ item }}
      with_items:
        - websocketd
        - hooks.yml
        - log.txt

    - name: Making sure SSH connection is not disturbed
      ufw:
        rule: allow
        name: OpenSSH

    - name: Firewall allow port range 4440-4450
      ufw:
        state: enabled
        rule: allow
        port: 4440:4450
        proto: tcp