---
- name: Send the necessary files.
  hosts: all
  tasks:
    - name: Create t2d directory
      file:
        path: /opt/t2d
        state: directory

    - name: Uploading files to users server
      copy:
        src: ../../../lib/{{ item }}
        dest: /opt/t2d/{{ item }}
      with_items:
        - websocketd
        - hooks.yml
        - log.txt

    - name: Firewall allow port for ssh, web(http, https), t2d services
      ufw:
        state: enabled
        rule: allow
        port: "{{ item }}"
        proto: tcp
        with_items:
          - 22
          - 80
          - 443
          - 4443
          - 4444
          - 4445