---
- name: Configuring Websocketd
  hosts: all
  tasks:

    - name: Making the websocket executable.
      shell: 'chmod a+x /opt/t2d/websocketd'

    - name: Starting websocketd in background.
      shell: 'nohup /opt/t2d/websocketd -port=4444 tail -f /opt/t2d/log.txt > /opt/t2d/websocketd.log &'

    # Variables, need to be provided => userID

    # - name: Making the websocket executable.
    #   shell: "{{ item }}"
    #   with_items: 
    #     - sudo dokku plugin:install https://github.com/dokku/dokku-letsencrypt.git
    #     - dokku apps:create t2d
    #     - docker build -t dokku/t2d /opt/t2d
    #     - dokku domains:set t2d t2d-{{ userID }}.leewardslope.com
    #     - dokku proxy:ports-set t2d http:80:4444 https:443:4444
    #     - mkdir /var/lib/dokku/data/storage/t2d
    #     - cp -r /opt/t2d /var/lib/dokku/data/storage
    #     - chown dokku:dokku /var/lib/dokku/data/storage/t2d
    #     - dokku storage:mount t2d /var/lib/dokku/data/storage/t2d:/usr/src/app
    #     - dokku config:set t2d --no-restart DOKKU_LETSENCRYPT_EMAIL=admin@leewardslope.com
    #     - dokku letsencrypt:enable t2d
    #     - dokku tags:deploy t2d latest
    #   ignore_errors: True
    #   async: 1000 # Maximum allowed time in Seconds
    #   poll: 25