---
- hosts: all
  tasks:
    - name: Adding Scale
      shell: dokku ps:scale {{ appName }} {{ serviceName }}={{ value }}
      ignore_errors: True
      async: 60 # Maximum allowed time in Seconds
      poll: 5