---
- hosts: all
  tasks:
    - name: initializing git
      shell: dokku git:initialize {{ appTitle }}
      ignore_errors: True

    - name: Allowing github
      shell: dokku git:allow-host github.com
      ignore_errors: True

    - name: Setting the branch to main
      shell: dokku git:set {{ appTitle }} deploy-branch main
      ignore_errors: True
