---

- hosts: master

  tasks:
    - name: Read a json file
      set_fact:
        my_json_contents: "{{ lookup('file', './{{ file }}.json') }}"

    - name: What did we read?
      debug:
        var: my_json_contents

    - name: Ping each IP
      shell: echo {{ item.IP }} = {{ item.name }} >> looptest.txt
      with_items: "{{ my_json_contents }}"
    